#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'apt'
cookbook 'nginx'
cookbook 'python'
cookbook 'redis'
cookbook 'rabbitmq'
cookbook 'application'
cookbook 'application_python'
cookbook 'application_nginx'
cookbook 'postgresql', :git => "https://github.com/phlipper/chef-postgresql.git"
